[package]
name = "swc-coverage-instrument-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
swc-coverage-instrument = { version = "0.0.4", path = "../../packages/swc-coverage-instrument" }
serde-wasm-bindgen = "0.4.2"
