[workspace]
exclude = ["spec/swc-coverage-custom-transform"]
members = [
  "packages/swc-plugin-coverage",
  "packages/istanbul-oxide",
  "packages/swc-coverage-instrument",
  "spec/swc-coverage-instrument-wasm",
]

[profile.release]
lto = true
