[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage data struct"
edition     = "2021"
license     = "MIT"
name        = "istanbul-oxide"
repository  = "https://github.com/kwonoj/swc-coverage-instrument"
version     = "0.0.15"

[dependencies]
indexmap = { version = "1.9.2", features = ["serde"] }
serde    = { version = "1.0.151", features = ["derive"] }
