[package]
name = "istanbul-oxide"
version = "0.0.4"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage data struct"
license = "MIT"
repository = "https://github.com/kwonoj/swc-coverage-instrument"

[dependencies]
indexmap = { version = "1.8.1", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
