[package]
name = "swc-plugin-istanbul-oxi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# instruct dep to use swc_plugin as dependency to access necessary imports
istanbul-oxi-instrument = { version = "0.1.0", path = "../istanbul-oxi-instrument", features = ["plugin"], default-features = false }
once_cell = "1.10.0"
regex = "1.5.5"
serde = "1.0.136"
serde_json = "1.0.79"
swc_ecma_quote = "0.14.0"
swc_plugin = { version = "0.49.0", features = ["quote"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["fmt"] }

[dev-dependencies]
pretty_assertions = "1.2.1"

[features]
