[package]
name = "swc-plugin-coverage"
version = "0.0.1"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation plugin for SWC"
license = "MIT"
repository = "https://github.com/kwonoj/swc-coverage-instrument"

[lib]
crate-type = ["cdylib"]

[dependencies]
# instruct dep to use swc_plugin as dependency to access necessary imports
swc-coverage-instrument = { version = "0.0.2", path = "../swc-coverage-instrument", features = [
  "plugin",
], default-features = false }
serde_json = "1.0.79"
swc_plugin = { version = "0.49.0", features = ["quote"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["fmt"] }