[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation plugin for SWC"
edition     = "2021"
license     = "MIT"
name        = "swc-plugin-coverage"
repository  = "https://github.com/kwonoj/swc-coverage-instrument"
version     = "0.0.15"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json              = "1.0.90"
swc-coverage-instrument = { version = "0.0.15", path = "../swc-coverage-instrument" }
swc_core                = { version = "0.69.30", features = ["ecma_plugin_transform"] }
tracing                 = "0.1.37"
tracing-subscriber      = { version = "0.3.16", features = ["fmt"] }
