[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation plugin for SWC"
edition     = "2021"
license     = "MIT"
name        = "swc-plugin-coverage"
repository  = "https://github.com/kwonoj/swc-coverage-instrument"
version     = "0.0.12"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json              = "1.0.85"
swc-coverage-instrument = { version = "0.0.12", path = "../swc-coverage-instrument" }
swc_core                = { version = "0.27.9", features = ["plugin_transform"] }
tracing                 = "0.1.36"
tracing-subscriber      = { version = "0.3.15", features = ["fmt"] }
