[package]
name = "swc-coverage-instrument"
version = "0.0.3"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation visitor for SWC"
license = "MIT"
repository = "https://github.com/kwonoj/swc-coverage-instrument"

[features]
default = ["swc_common"]
plugin = []

[dependencies]
istanbul-oxide = { version = "0.0.3", path = "../istanbul-oxide" }
once_cell = "1.10.0"
regex = "1.5.5"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }

swc_common = { version = "0.17.25", optional = true }
swc_plugin = { version = "0.49.0", features = ["quote"] }
swc_ecma_quote = "0.14.0"
tracing = "0.1.34"

[dev-dependencies]
pretty_assertions = "1.2.1"
