[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation visitor for SWC"
edition     = "2021"
license     = "MIT"
name        = "swc-coverage-instrument"
repository  = "https://github.com/kwonoj/swc-coverage-instrument"
version     = "0.0.12"

[dependencies]
istanbul-oxide = { version = "0.0.12", path = "../istanbul-oxide" }
once_cell      = "1.15.0"
regex          = "1.6.0"
serde          = { version = "1.0.145", features = ["derive"] }
serde_json     = "1.0.85"

swc_core = { version = "0.27.9", features = [
  "common",
  "ecma_quote",
  "ecma_visit",
  "ecma_utils",
  "ecma_ast",
] }
tracing = "0.1.36"

[dev-dependencies]
pretty_assertions = "1.3.0"
