[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation visitor for SWC"
edition     = "2021"
license     = "MIT"
name        = "swc-coverage-instrument"
repository  = "https://github.com/kwonoj/swc-coverage-instrument"
version     = "0.0.18"

[dependencies]
istanbul-oxide = { version = "0.0.18", path = "../istanbul-oxide" }
once_cell      = "1.17.1"
regex          = "1.8.1"
serde          = { version = "1.0.160", features = ["derive"] }
serde_json     = "1.0.96"

swc_core = { workspace = true, features = [
  "common",
  "ecma_quote",
  "ecma_visit",
  "ecma_utils",
  "ecma_ast",
] }
tracing = "0.1.37"

[dev-dependencies]
pretty_assertions = "1.3.0"
