[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation visitor for SWC"
edition     = "2021"
license     = "MIT"
name        = "swc-coverage-instrument"
repository  = "https://github.com/kwonoj/swc-coverage-instrument"
version     = "0.0.8"

[dependencies]
istanbul-oxide = { version = "0.0.8", path = "../istanbul-oxide" }
once_cell      = "1.13.1"
regex          = "1.6.0"
serde          = { version = "1.0.143", features = ["derive"] }
serde_json     = "1.0.83"

swc_core = { version = "0.7.20", features = [
  "quote",
  "common",
  "visit",
  "utils",
  "ast",
] }
tracing = "0.1.36"
[dev-dependencies]
pretty_assertions = "1.2.1"
