[package]
name = "swc-coverage-instrument"
version = "0.0.4"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation visitor for SWC"
license = "MIT"
repository = "https://github.com/kwonoj/swc-coverage-instrument"

[dependencies]
istanbul-oxide = { version = "0.0.4", path = "../istanbul-oxide" }
once_cell = "1.10.0"
regex = "1.5.5"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }

swc_common = { version = "0.17.25" }
swc_ecma_quote = "0.15.0"
tracing = "0.1.34"
swc_ecma_visit = "0.63.0"
swc_ecma_ast = "0.77.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
