[package]
name = "swc-coverage-instrument"
version = "0.0.6"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation visitor for SWC"
license = "MIT"
repository = "https://github.com/kwonoj/swc-coverage-instrument"

[dependencies]
istanbul-oxide = { version = "0.0.6", path = "../istanbul-oxide" }
once_cell = "1.10.0"
regex = "1.5.5"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }

swc_common = { version = "0.18.2", features = ["sourcemap"] }
swc_ecmascript = { version = "0.157.0", features = ["utils", "visit"] }
swc_ecma_quote = "0.17.0"
tracing = "0.1.34"
swc_ecma_ast = "0.78.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
